"use client"

import { motion } from "framer-motion"
import { Copy, Download, Check, Sparkles, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"

interface TranscriptOutputProps {
  transcript: string
  videoTitle: string
  onCopy: () => void
  onDownload: () => void
  copied: boolean
  usedGemini: boolean
}

export function TranscriptOutput({
  transcript,
  videoTitle,
  onCopy,
  onDownload,
  copied,
  usedGemini,
}: TranscriptOutputProps) {
  const wordCount = transcript.split(/\s+/).filter(Boolean).length
  const charCount = transcript.length

  // Format transcript with better paragraph breaks
  const formatTranscript = (text: string) => {
    // Split by sentences and group them into paragraphs
    const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]
    const paragraphs: string[] = []
    let currentParagraph: string[] = []

    sentences.forEach((sentence, index) => {
      currentParagraph.push(sentence.trim())

      // Create a new paragraph every 3-4 sentences
      if (currentParagraph.length >= 3 || index === sentences.length - 1) {
        paragraphs.push(currentParagraph.join(" "))
        currentParagraph = []
      }
    })

    return paragraphs.filter(p => p.trim())
  }

  const paragraphs = formatTranscript(transcript)

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.5 }}
      className="mb-12"
    >
      <div className="border border-zinc-800 bg-zinc-950 shadow-2xl shadow-purple-500/5 rounded-lg overflow-hidden">
        {/* Header */}
        <div className="border-b border-zinc-800 p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-zinc-900/50">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center rounded">
              {usedGemini ? (
                <Sparkles className="w-4 h-4 text-white" />
              ) : (
                <FileText className="w-4 h-4 text-white" />
              )}
            </div>
            <div>
              <h3 className="font-mono text-sm font-medium text-white truncate max-w-xs">{videoTitle}</h3>
              <p className="font-mono text-xs text-zinc-500">
                {wordCount.toLocaleString()} words • {charCount.toLocaleString()} characters
                {usedGemini && " • Generated by Gemini"}
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={onCopy} className="font-mono text-xs bg-zinc-900 border-zinc-700 text-white hover:bg-zinc-800">
              {copied ? (
                <>
                  <Check className="w-3 h-3 mr-1.5 text-green-400" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3 mr-1.5" />
                  Copy
                </>
              )}
            </Button>
            <Button variant="outline" size="sm" onClick={onDownload} className="font-mono text-xs bg-zinc-900 border-zinc-700 text-white hover:bg-zinc-800">
              <Download className="w-3 h-3 mr-1.5" />
              Download
            </Button>
          </div>
        </div>

        {/* Content */}
        <div className="p-8 max-h-[600px] overflow-y-auto bg-black custom-scrollbar">
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }}>
            <div className="prose prose-invert max-w-none">
              {paragraphs.map((paragraph, index) => (
                <p
                  key={index}
                  className="text-base leading-relaxed text-zinc-300 mb-4 last:mb-0 font-sans"
                >
                  {paragraph}
                </p>
              ))}
            </div>
          </motion.div>
        </div>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #18181b;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #3f3f46;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #52525b;
        }
      `}</style>
    </motion.div>
  )
}
